import type { Rule } from "./types";

export const rules: Rule[] = [
  {
    id: "LM-001",
    declaration: "Product Identity",
    requirement: "Product name must be clearly declared on the label",
    validationType: "presence",
    severity: "high",
    status: "active",
    category: "Mandatory",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "The Legal Metrology (Packaged Commodities) Rules require that every packaged commodity must bear the name of the product in a clear and unambiguous manner.",
    validationLogic: "OCR extraction + semantic verification of product name presence and clarity",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-002",
    declaration: "Manufacturer Details",
    requirement: "Name and address of manufacturer/prepacker/importer must be declared",
    validationType: "presence",
    severity: "high",
    status: "active",
    category: "Mandatory",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Manufacturer, pre-packer, or importer name with complete postal address must be visible on the label.",
    validationLogic: "OCR extraction + presence check for both name AND address components",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-003",
    declaration: "Net Quantity",
    requirement: "Net quantity must be declared in standard SI units",
    validationType: "ocr-format",
    severity: "high",
    status: "active",
    category: "Quantity",
    version: "2.1",
    effectiveDate: "2024-06-01",
    description: "Net quantity must be expressed in SI units (g, kg, ml, L) or legal units of measurement as specified in Schedule II.",
    validationLogic: "OCR extraction + unit validation against SI standards + format check",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
      { version: "2.0", status: "archived", effectiveDate: "2024-01-01" },
    ],
  },
  {
    id: "LM-004",
    declaration: "MRP Declaration",
    requirement: "Maximum Retail Price must be declared in ₹ with tax inclusion",
    validationType: "ocr-format",
    severity: "high",
    status: "active",
    category: "Price",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "MRP must include ₹ symbol and the text '(Inclusive of all taxes)' or equivalent declaration. Missing either component constitutes a violation.",
    validationLogic: "OCR extraction + ₹ symbol presence + tax inclusion text verification",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-005",
    declaration: "Consumer Care Details",
    requirement: "Consumer care contact information (phone/email) must be present",
    validationType: "presence",
    severity: "high",
    status: "active",
    category: "Consumer",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "A consumer care contact — phone number, email, or postal address — must be provided for consumer grievance redressal.",
    validationLogic: "OCR extraction + phone/email pattern detection + presence threshold",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-006",
    declaration: "Date Declaration",
    requirement: "Manufacturing/packing date and expiry/use-before date must be declared",
    validationType: "ocr-format",
    severity: "high",
    status: "active",
    category: "Date",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Manufacturing or packing date must be present. For products with shelf life, expiry or 'use before' date is also required.",
    validationLogic: "OCR extraction + date format validation (DD/MM/YYYY or MMM/YYYY) + perishability check",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-007",
    declaration: "Country of Origin",
    requirement: "Country of origin must be declared on the package",
    validationType: "ocr-presence",
    severity: "medium",
    status: "active",
    category: "Mandatory",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "The country where the product was manufactured or assembled must be clearly stated.",
    validationLogic: "OCR extraction + semantic check for country origin patterns",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-008",
    declaration: "Batch/Lot Number",
    requirement: "Batch or lot number must be clearly marked",
    validationType: "presence",
    severity: "medium",
    status: "active",
    category: "Mandatory",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "A batch or lot identification number must be present for traceability purposes.",
    validationLogic: "OCR extraction + alphanumeric pattern detection",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-009",
    declaration: "Vegetarian/Non-Veg Mark",
    requirement: "Mandatory vegetarian/non-vegetarian declaration symbol",
    validationType: "presence",
    severity: "medium",
    status: "active",
    category: "Food",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Food products must display the mandatory green dot (vegetarian) or brown dot (non-vegetarian) symbol.",
    validationLogic: "OCR + visual pattern detection for dot symbol",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-010",
    declaration: "FSSAI License",
    requirement: "FSSAI license number for food products",
    validationType: "ocr-format",
    severity: "high",
    status: "active",
    category: "Food",
    version: "2.1",
    effectiveDate: "2024-06-01",
    description: "Food products must display a valid 14-digit FSSAI license/registration number.",
    validationLogic: "OCR extraction + 14-digit number validation + FSSAI prefix check",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
      { version: "2.0", status: "archived", effectiveDate: "2024-01-01" },
    ],
  },
  {
    id: "LM-011",
    declaration: "MRP Prefix",
    requirement: "MRP must be prefixed with '₹' symbol",
    validationType: "ocr-format",
    severity: "low",
    status: "active",
    category: "Price",
    version: "1.0",
    effectiveDate: "2022-06-01",
    description: "The MRP value must be preceded by the Indian Rupee symbol ₹.",
    validationLogic: "OCR extraction + ₹ symbol prefix check",
    previousVersions: [],
  },
  {
    id: "LM-012",
    declaration: "Date Format",
    requirement: "Dates must follow DD/MM/YYYY or MMM/YYYY format",
    validationType: "ocr-format",
    severity: "low",
    status: "active",
    category: "Date",
    version: "1.0",
    effectiveDate: "2022-06-01",
    description: "Date declarations must use standard Indian date formats.",
    validationLogic: "OCR extraction + regex format validation",
    previousVersions: [],
  },
];

export function generateInspectionId(): string {
  const num = Math.floor(Math.random() * 90000) + 10000;
  return `INS-2026-${num}`;
}

export function generateAuditId(): string {
  return `AUD-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`;
}
