import type { Rule } from "./types";

/**
 * Legal Metrology (Packaged Commodities) Rules, 2011
 * Rules 6 through 13 — as per the actual legal text.
 * Each rule maps to a specific legal provision for enforcement.
 */
export const rules: Rule[] = [
  {
    id: "LM-001",
    declaration: "Manufacturer/Packer/Importer Name & Address",
    requirement: "Name and complete address of manufacturer, or manufacturer + packer, or importer must be declared. Address must include street, city, state, and PIN code.",
    validationType: "presence",
    severity: "high",
    status: "active",
    category: "Mandatory Declarations",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 6(1)(a) — Every package shall bear the name and address of the manufacturer, or where the manufacturer is not the packer, the name and address of the manufacturer and packer and for any imported package the name and address of the importer. 'Complete address' means postal address including street, city, state and PIN code.",
    validationLogic: "OCR extraction + presence check for both name AND complete address components (street, city, state, PIN)",
  },
  {
    id: "LM-002",
    declaration: "Product Identity (Common/Generic Name)",
    requirement: "The common or generic name of the commodity must be declared. For multi-product packages, name and quantity of each product must be mentioned.",
    validationType: "presence",
    severity: "high",
    status: "active",
    category: "Mandatory Declarations",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 6(1)(b) — The common or generic names of the commodity contained in the package and in case of packages with more than one product, the name and number or quantity of each product shall be mentioned on the package.",
    validationLogic: "OCR extraction + semantic verification of product name presence and clarity",
  },
  {
    id: "LM-003",
    declaration: "Net Quantity Declaration",
    requirement: "Net quantity must be declared in standard SI units: mass (g/kg) for solids, volume (ml/L) for liquids, length (cm/m) for linear, area (cm²/m²) for area, or number (N/U) for count. Must not use qualifying words like 'minimum', 'about', 'approximately'.",
    validationType: "ocr-format",
    severity: "high",
    status: "active",
    category: "Quantity Declaration",
    version: "3.0",
    effectiveDate: "2024-06-01",
    description: "Rule 6(1)(c) + Rule 11 + Rule 12 — Net quantity must be in standard SI units. The declaration shall not contain words like 'minimum', 'not less than', 'average', 'about', 'approximately' which create exaggerated, misleading or inadequate impression as to the quantity.",
    validationLogic: "OCR extraction + SI unit validation + qualifying word detection + format check",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
      { version: "2.0", status: "archived", effectiveDate: "2024-01-01" },
    ],
  },
  {
    id: "LM-004",
    declaration: "Manufacturing/Packing Date",
    requirement: "Month and year of manufacture, packing, or import must be declared. Can be in words, numerals, or both. For food products with 'best before' ≤ 90 days, special packaging material rules apply.",
    validationType: "ocr-format",
    severity: "high",
    status: "active",
    category: "Date Declarations",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 6(1)(d) — The month and year in which the commodity is manufactured or pre-packed or imported shall be mentioned. May be expressed in words, numerals, or both. Exemption: bidis, incense sticks, and domestic LPG cylinders (14.2kg/5kg) by public sector undertakings.",
    validationLogic: "OCR extraction + date format validation (DD/MM/YYYY or MMM/YYYY)",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-005",
    declaration: "Retail Sale Price (MRP)",
    requirement: "MRP must include ₹ symbol and '(Inclusive of all taxes)' text. A sticker reducing MRP is permitted but must not cover original MRP declaration.",
    validationType: "ocr-format",
    severity: "high",
    status: "active",
    category: "Price Declaration",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 6(1)(e) — The retail sale price of the package shall be mentioned. For reducing the MRP, a sticker with the revised lower MRP (inclusive of all taxes) may be affixed and shall not cover the MRP declaration by the manufacturer. Exemption: bidis, domestic LPG under Administrative Price Mechanism, and alcoholic beverages governed by State Excise Laws.",
    validationLogic: "OCR extraction + ₹ symbol presence + tax inclusion text verification",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-006",
    declaration: "Consumer Care Contact Details",
    requirement: "Name, address, telephone number, and email address (if available) of the person/office to be contacted for consumer complaints must be declared.",
    validationType: "presence",
    severity: "high",
    status: "active",
    category: "Consumer Information",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 6(2) — Every package shall bear the name, address, telephone number, e-mail address, if available, of the person who can be or the office which can be contacted, in case of consumer complaints.",
    validationLogic: "OCR extraction + phone/email pattern detection + presence threshold",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-007",
    declaration: "No Unauthorized Sticker Alterations",
    requirement: "Individual stickers shall NOT be used to alter or make declarations required under these rules. Exception: MRP reduction sticker is permitted (must not cover original MRP).",
    validationType: "presence",
    severity: "medium",
    status: "active",
    category: "Label Integrity",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 6(3) + Rule 6(4) — It shall not be permissible to affix individual stickers on the package for altering or making declaration required under these rules. Provided that for reducing the MRP, a sticker with the revised lower MRP may be affixed. Stickers may be used for declarations other than mandatory ones.",
    validationLogic: "Visual inspection + OCR detection for sticker overlays on required declarations",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-008",
    declaration: "Declaration Legibility & Contrast",
    requirement: "All declarations must be legible and prominent. Numerals for MRP and net quantity must be printed in a contrasting color. Minimum letter height: 1mm (2mm when blown/molded).",
    validationType: "semantic",
    severity: "medium",
    status: "active",
    category: "Label Quality",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 9(1)(a) + Rule 9(1)(b) — Every declaration shall be legible and prominent; numerals of the retail sale price and net quantity shall be printed in a colour that contrasts conspicuously with the background. Height of letters not less than 1mm (2mm when blown/molded). Glass/plastic with molded info exempt from contrasting colour.",
    validationLogic: "OCR confidence analysis + visual contrast detection + minimum size verification",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-009",
    declaration: "Country of Origin",
    requirement: "Country where the product was manufactured or assembled must be clearly stated on the package.",
    validationType: "ocr-presence",
    severity: "medium",
    status: "active",
    category: "Mandatory Declarations",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 6(1)(g) — Such other matter as are specified in these rules shall be declared. Country of origin is a mandatory declaration for all packaged commodities.",
    validationLogic: "OCR extraction + semantic check for country origin patterns",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-010",
    declaration: "Batch/Lot Number",
    requirement: "Batch or lot identification number must be present for traceability purposes.",
    validationType: "presence",
    severity: "medium",
    status: "active",
    category: "Mandatory Declarations",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Required for traceability — a batch or lot number must be clearly marked on every pre-packed commodity for recall and quality tracking.",
    validationLogic: "OCR extraction + alphanumeric pattern detection",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-011",
    declaration: "Vegetarian/Non-Veg Mark",
    requirement: "Food products must display the mandatory green dot (vegetarian) or brown dot (non-vegetarian) symbol.",
    validationType: "presence",
    severity: "medium",
    status: "active",
    category: "Food Compliance",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Required for all food products — the mandatory vegetarian (green dot/square) or non-vegetarian (brown dot/square) symbol must be displayed prominently on the package.",
    validationLogic: "OCR + visual pattern detection for dot symbol",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-012",
    declaration: "FSSAI License Number",
    requirement: "Food products must display a valid 14-digit FSSAI license/registration number.",
    validationType: "ocr-format",
    severity: "high",
    status: "active",
    category: "Food Compliance",
    version: "3.0",
    effectiveDate: "2024-06-01",
    description: "Under the Food Safety and Standards Act, 2006 and FSSAI regulations, food products must display a valid 14-digit FSSAI license or registration number on the label.",
    validationLogic: "OCR extraction + 14-digit number validation + FSSAI prefix check",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
      { version: "2.0", status: "archived", effectiveDate: "2024-01-01" },
    ],
  },
  {
    id: "LM-013",
    declaration: "Expiry / Best Before Date",
    requirement: "For products with limited shelf life, expiry date or 'best before'/'use before' date must be declared. For food products with shelf life ≤ 90 days, special packaging rules apply.",
    validationType: "ocr-format",
    severity: "high",
    status: "active",
    category: "Date Declarations",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 6(1)(d) + FSSAI — For packages containing food articles, provisions of the Prevention of Food Adulteration Act apply. Products with limited shelf life must declare expiry or 'use before' date. Shelf life ≤ 90 days: packaging material from previous month cannot be reused.",
    validationLogic: "OCR extraction + date format validation + perishability check",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-014",
    declaration: "Correct SI Unit Usage",
    requirement: "Units must follow SI standards: mass in g (under 1kg) or kg (1kg+); volume in ml (under 1L) or L (1L+); length in cm (under 1m) or m (1m+). Dozen, score, gross are prohibited. Items sold by number must use 'N' or 'U'.",
    validationType: "ocr-format",
    severity: "high",
    status: "active",
    category: "Quantity Declaration",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 13 — The units shall be specified in accordance with SI units. No system other than International System of Units shall be used. No number called the dozen, score, gross, great gross shall be specified. Items sold by number must use symbol N or U.",
    validationLogic: "OCR extraction + SI unit validation + prohibited unit detection",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-015",
    declaration: "Principal Display Panel Requirements",
    requirement: "Declarations must appear on the principal display panel. Quantity declaration area must have clearance: space equal to numeral height above/below, twice numeral height left/right. Min numeral height per Table-I and Table-II.",
    validationType: "semantic",
    severity: "medium",
    status: "active",
    category: "Label Quality",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 7 + Rule 8 — Every declaration shall appear on the principal display panel. Area surrounding quantity declaration shall be free from printed information — above/below by space equal to numeral height, left/right by space twice the numeral height. Packages ≤ 5 cubic cm may use affixed card/tape.",
    validationLogic: "Visual layout analysis + declaration placement verification",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
  {
    id: "LM-016",
    declaration: "Dimensions (When Relevant)",
    requirement: "Where the sizes of the commodity are relevant, the dimensions must be declared. If different pieces have different dimensions, each must be mentioned separately.",
    validationType: "ocr-presence",
    severity: "medium",
    status: "active",
    category: "Mandatory Declarations",
    version: "2.0",
    effectiveDate: "2024-01-01",
    description: "Rule 6(1)(f) — Where the sizes of the commodity contained in the package are relevant, the dimensions of the commodity contained in the package and if the dimensions of the different pieces are different, the dimensions of each such different piece shall be mentioned.",
    validationLogic: "OCR extraction + dimension pattern detection",
    previousVersions: [
      { version: "1.0", status: "archived", effectiveDate: "2022-06-01" },
    ],
  },
];

export function generateInspectionId(): string {
  const num = Math.floor(Math.random() * 90000) + 10000;
  return `INS-2026-${num}`;
}

export function generateAuditId(): string {
  return `AUD-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`;
}
